# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelperApp', '0002_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
