# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelperApp', '0003_jobs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='HandyHelperApp.Users'),
            preserve_default=False,
        ),
    ]
